# Generated by Django 3.0.5 on 2020-05-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20200511_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='insta_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
