# Generated by Django 3.0.5 on 2020-05-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20200511_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='twitter_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
