# Generated by Django 3.0.5 on 2020-05-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20200511_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='whatsapp_profile',
            new_name='linkedin_profile',
        ),
    ]
