# Generated by Django 3.0.5 on 2020-05-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20200511_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.CharField(blank=True, default='Not provided', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, default='Not provided', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='Not provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_profile',
            field=models.CharField(blank=True, default='#', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta_profile',
            field=models.CharField(blank=True, default='#', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_profile',
            field=models.CharField(blank=True, default='#', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.CharField(blank=True, default='Not provided', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_profile',
            field=models.CharField(blank=True, default='#', max_length=200, null=True),
        ),
    ]
