# Generated by Django 3.0.5 on 2020-05-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20200512_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
