# Generated by Django 3.0.5 on 2020-05-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20200521_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unread_post_count',
            field=models.IntegerField(default=0),
        ),
    ]
