# Generated by Django 3.0.5 on 2020-06-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20200521_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_visited',
            field=models.DateTimeField(null=True),
        ),
    ]
