# Generated by Django 3.2.5 on 2022-03-20 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_auto_20200613_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_visited',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 12, 4, 57, 43477), null=True),
        ),
    ]
