# Generated by Django 3.0.5 on 2020-05-13 12:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
        migrations.RenameModel(
            old_name='PostImages',
            new_name='PostImage',
        ),
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
    ]
