# Generated by Django 3.0.5 on 2020-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_postcomment_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment_text',
            field=models.TextField(),
        ),
    ]
