# Generated by Django 3.0.5 on 2020-05-18 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20200515_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 10, 32, 12, 415136, tzinfo=utc)),
        ),
    ]
